=== marco-ballario/dsp-labs/Lab01/schemas/task.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://dsp.polito.it/task.json",
    "type": "object",
    "properties": {
        "id": {
            "type": "integer"
        },
        "description": {
            "type": "string",
            "maxLength": 160
        },
        "important": {
            "type": "boolean",
            "default": false
        },
        "private": {
            "type": "boolean",
            "default": true
        },
        "projects": {
            "type": "array",
            "items": {
                "enum": [
                    "Personal",
                    "WA1_Project",
                    "WA2_Project",
                    "DSP_Project"
                ]
            }
        },
        "deadline": {
            "type": "string",
            "format": "date"
        },
        "completed": {
            "type": "boolean",
            "default": false
        },
        "owner": {
            "type": "integer"
        },
        "assignedTo": {
            "type": "integer"
        }
    },
    "required": [
        "id",
        "description"
    ]
}

=== marco-ballario/dsp-labs/Lab01/schemas/test_task.json
{
    "$schema": "./task.json",
    "id": 5,
    "description": "ciao",
    "important": true,
    "private": false,
    "projects": [
        "DSP_Project",
        "DSP_Project",
        "DSP_Project"
    ],
    "deadline": "2020-10-25",
    "completed": true,
    "owner": 3,
    "assignedTo": 5
}
